### ISSUE TITLE
Consider switching to catppuccin theme

### ISSUE THREAD

**Issue by trinkey** [trinkey/social-media-thing#102]
https://catppuccin-website.vercel.app/

i mean it looks good and then we don't have to worry about colors and whatnot in the future

this would require rewriting a lot of the frontend css stuff, however it's not the worst thing ever

this would also mean we no longer need the color feature, however this would also mean there would be four main themes (latte (light), frappé (gray), macchiato (dark), mocha (midnight))

@Subroutine7901 lmk what you think

**Comment by Subroutine7901** [comment]
Not a bad idea, but I work backend mainly so it'd probably be on you to get it working frontend

**Comment by trinkey** [comment]
good with me, im fine doing it all

**Comment by trinkey** [comment]
@Subroutine7901 i finished the rewrite, if you want to merge it into django-rewrite you can, although you can just finish that and i can merge it at the end if you want

it really shouldn't be hard, you just need to copy over frontend files and change the theme validation backend from checking against `["light", "dark"]` to `["light", "gray", "dark", "black"]`

**Comment by trinkey** [comment]
and also add templating for `/settings` to select the correct item from the dropdown
