### ISSUE TITLE
Allow setting path for static files

### ISSUE THREAD

**Issue by trinkey** [trinkey/social-media-thing#103]
would be placed before static urls (css, js, img) like `{{ ROUTE }}/css/base.css`

this would be used if someone wanted to like specify a specific cdn server

**Comment by Subroutine7901** [comment]
I uh django has this built in uhhh but yea

**Comment by Subroutine7901** [comment]
This might be confusing because it's a thing that the webserver does/needs to know
and it's just like really dependent on that so idk
