### ISSUE TITLE
more user-friendly admin page

### ISSUE THREAD

**Issue by trinkey** [trinkey/social-media-thing#122]
make a new admin page (user ids that can access it can be configured in _settings.py)

could have multiple levels of access, for example:
1. can change who has what icons or whatever (when added in #104)
2. can force delete any post or comment (along with one)
3. can also change any user information (bio from #52, displ name, banner colors, etc.)
4. can also log in to and delete any user account (maybe add a button that adds an account by username to your account switcher from #75?)

@Subroutine7901 i'd probably give you 2-3, the only reason i'm hesitant doing it now is because you would have access to literally everything, feel free to adjust priority to how you see fit, mostly because you're the one who really wants this

**Comment by Subroutine7901** [comment]
If we add custom banners / pfps later down the line (like wayy later, probably /w pateron donos) then this would be a good place to put the approval queue for those bc We'd really need one

**Comment by Subroutine7901** [comment]
But ngl we'd need some kind of auth for all of the new requests coming from this page. I'd say we first get the account switcher and any other issues this one might depend on done, bc this is a large undertaking and warrants like 5.0 with all its gonna be adding, (assuming we end up adding like pfps and/or image banners too, or some other user features)

**Comment by Subroutine7901** [comment]
Oh yea
@trinkey

**Comment by trinkey** [comment]
i dont plan on adding images or whatever anytime soon but im def willing to start working on this just in general

**Comment by trinkey** [comment]
when doing this it might be worth just doing #120 at the same time because they're similar

**Comment by trinkey** [comment]
true
