### ISSUE TITLE
allow deleting posts and accounts

### ISSUE THREAD

**Issue by trinkey** [trinkey/social-media-thing#14]

**Comment by trinkey** [comment]
might be done by just making the user files empty or simulating a user that hasn't done anything, deleted posts might just replace the post file with `{"deleted": null}` or something

**Comment by Subroutine7901** [comment]
I'd say for users you could replace all the info with a placeholder, and add a deleted bool that adds a tag in the site that it's a deleted user

**Comment by Subroutine7901** [comment]
maybe something like that for posts?

**Comment by Subroutine7901** [comment]
you have to do it like this (not just removing it) for ID continuity

**Comment by Subroutine7901** [comment]
Counting up like that, for posts and users, isn't the best idea, maybe you could change ids to just hashes of a post/random for users, and just add a check for if it's been used, in that small chance that it's a duped hash.

**Comment by Subroutine7901** [comment]
(messages, for example would be a hash of some of the attributes, content, creator, and most importantly timestamp, to prevent dupe hashes from happening intentionally.

**Comment by trinkey** [comment]
I forgot to reply to this but:
1. Users should be very easy as id is only used backend, just deleting the files for it should be all it needs. ids are only for identification and not discovery
2. for posts, placeholders that are parsed out backend are probably best
3. i get the security issues with post/comment ids counting up, although it is incredibly convenient. I could make some list thing that makes the recent tab work although idk, level ids in geometry dash are sequential and that doesn't seem to be very bad. user ids are never accessed frontend iirc so that shouldn't matter.

**Comment by Subroutine7901** [comment]
Yeah, I think moving to a db would be best long term because of both convenience and functionality. Sequential ids isn't really a security hole, (roblox, gd, many other questionably coded projects) use it, and they've lived, but it's just good practice not to. A db would also make the disk efficiency better, and solve the deletion issue more easily. (Possible security hole if users can issue a database row deletion though.) Until then, deleted posts/users could affect front end by adding a redirect or something on the page indicating the object is deleted, like how Twitter puts "this post is deleted" sometimes.

**Comment by trinkey** [comment]
another option to make the sequentiality not an issue is we could make it be /p/username/id where the username has to be correct for the post to be viewed

but yes database

**Comment by Subroutine7901** [comment]
So that each post id is unique to the user?

**Comment by Subroutine7901** [comment]
If we do that we would probably want to also make comments be bound to the post in the same way.

**Comment by trinkey** [comment]
i'm not sure how well flask handles multiple variables per url, because with one it's
```py
@app.route("/path/to/<path:var>")
def some_func(var):
    return flask.send_from_directory("path/to", var)
```
i'm assuming two will work although im not completely sure. if two doesn't work, we can do some funky stuff like `/[p|c]/id?user=username` but that's also inconvenient for the end user

but i still think we should have the global post id thing, with the username just ensuring that the end user knows who posted it. I will also have to probably update like one or two apis but yeah

**Comment by Subroutine7901** [comment]
should wait until #44 to solve

**Comment by Subroutine7901** [comment]
We need to test if we can just delete users and posts, but the list functions might throw a fit

**Comment by trinkey** [comment]
@Subroutine7901 we should do this with #122 too, ill self assign this for now
