### ISSUE TITLE
switch to an actual database instead of just files and json

### ISSUE THREAD

**Issue by trinkey** [trinkey/social-media-thing#44]

**Comment by DiamondTaco** [comment]
should probably use sqlite

**Comment by Subroutine7901** [comment]
Maybe make priority a little higher? I think we need to do this before we build more stuff off the id/file system that We'll need to fix and move over

**Comment by trinkey** [comment]
also you can make a script in /scripts/ if needed to easier translate current filesystem into a database

**Comment by Subroutine7901** [comment]
I uh
This escalated quickly
