### ISSUE TITLE
add user bios on profile

### ISSUE THREAD

**Issue by trinkey** [trinkey/social-media-thing#52]

**Comment by Subroutine7901** [comment]
Maybe just have this be the pinned posts? Idk if that would be practical

**Comment by trinkey** [comment]
good idea, i think bios would be easier, so pinned posts arent planned for now

**Comment by trinkey** [comment]
shouldn't be too hard to implement, just add a field like this
```py
#          (length configurable in settings)
bio = models.CharField(max_length=65536)
```

then frontend just add a div and template it in, maybe put it in the api_post_user function return so it auto updates, although still would need to template for the meta tags

**Comment by trinkey** [comment]
i forgot to close issue lol
