### ISSUE TITLE
admin console

### ISSUE THREAD

**Issue by trinkey** [trinkey/social-media-thing#67]
have a list in settings.json that has a list of ids that are allowed to visit it, if the user id isn't there return 404 (probably just `/admin` is fine)

have a link to it in `/settings` if user is admin

make it include:
- force banning users (after #14)
- force delete post/comment (after #14)
- force login to account (can be done with just returning an id and setting that as cookie)
- other stuff at some point

**Comment by Subroutine7901** [comment]
the django admin panel gives full db access and I think that would be enough to do all that manually
