### ISSUE TITLE
add profile button to icon bar

### ISSUE THREAD

**Issue by trinkey** [trinkey/social-media-thing#68]
like this for twitter
![image](https://github.com/trinkey/social-media-thing/assets/97406176/b77738ce-0e9e-40b1-afd1-40fc34a51c98)

**Comment by Subroutine7901** [comment]
I uh
![image](https://github.com/trinkey/social-media-thing/assets/77363873/33917531-50f3-46ff-a069-e0e2b3a9700c)
@trinkey

**Comment by trinkey** [comment]
that's before i restarted the server, you just got an in-between state where the public/... files were updated but the server hadn't restarted yet. it works if you reload

**Comment by Subroutine7901** [comment]
oh ok

**Comment by Subroutine7901** [comment]
still there

**Comment by trinkey** [comment]
try clearing localstorage

**Comment by Subroutine7901** [comment]
I uh
*how*

**Comment by trinkey** [comment]
```js
javascript:(() => { for (let i = 0; i < Object.keys(localStorage).length;) { localStorage.removeItem(Object.keys(localStorage)[i]) }})()
```

**Comment by Subroutine7901** [comment]
Time to run unchecked js code!

**Comment by Subroutine7901** [comment]
worked

**Comment by trinkey** [comment]
i should ensure that the response matches the regex for a username but eh later
