### ISSUE TITLE
allow viewing who someone follows and who follows them

### ISSUE THREAD

**Issue by trinkey** [trinkey/social-media-thing#71]
this requires using a `list[int]` instead of an `int` in `/save/users/123/settings.json` for the `followers` property

**Comment by Subroutine7901** [comment]
That's done in #110

**Comment by Subroutine7901** [comment]
Also add feature tag

**Comment by trinkey** [comment]
> That's done in #110

the lists, yes, but not any frontend stuff

**Comment by Subroutine7901** [comment]
> > That's done in #110
> 
> the lists, yes, but not any frontend stuff

I meant the lists
