### ISSUE TITLE
account switcher

### ISSUE THREAD

**Issue by trinkey** [trinkey/social-media-thing#75]
just change cookie and redir to home after clearing ls? idk

**Comment by Subroutine7901** [comment]
Make multiple token cookies? Like you can switch up to 3-5 accounts max and then we just have cookies token, token2-5, and then when you swap, the account tokens are swapped between token and the swapped account's token cookie

**Comment by trinkey** [comment]
i was thinking somehting more along the lines of keeping a json in localstorage or something that's like
```json
[
  { "username": "trinkey", "token": "abc123..." ),
  ...
]
```
also i think making a maximum of like 7 or 8 would be plenty although we don't *need* a max
