### ISSUE TITLE
Warning when clicking links

### ISSUE THREAD

**Issue by Crafternoobs** [trinkey/social-media-thing#91]
Add a warning when click link like discord will so people don’t accidentally go to a website that they don’t trust

**Comment by trinkey** [comment]
possible although in my opinion unneeded, especially as you cant disguise links as norm text its always the link itself.

also would need to use click events and make a modal and all that painful stuff

if we in the future add markdown support and can link like [this](https://example.com) then definitely will add

tldr; maybe later in the future although i see no need

**Comment by trinkey** [comment]
if you click on a link thats your fault

**Comment by trinkey** [comment]
good suggestion though will consider for the future
