### ISSUE TITLE
`/robots.txt` is treated as an HTML file

### ISSUE THREAD

**Issue by trinkey** [trinkey/social-media-thing#96]
`Content-Type` header is `text/html` instead of `text/plain`

![image](https://github.com/trinkey/social-media-thing/assets/97406176/86bd79bd-d7c5-45f1-9300-c2423cc7340e)

**Comment by Subroutine7901** [comment]
Webserver thing?
Idk

**Comment by trinkey** [comment]
it was caused by me using `create_file_serve()` with flask which treated it as `text/html`
