### ISSUE TITLE
Links and pings can conflict

### ISSUE THREAD

**Issue by Subroutine7901** [trinkey/social-media-thing#98]
![image](https://github.com/trinkey/social-media-thing/assets/77363873/aa270182-68b2-4f6b-bec5-44702c38e6fb)
If a link has an @ in it then it uh... parses it wrong.

**Comment by trinkey** [comment]
this is up to you i spent like 30 minutes writing regex for it so have fun!!!

**Comment by trinkey** [comment]
found this regex online and slightly modified it

```re
(https?:\/\/(?:www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b(?:[-a-zA-Z0-9@:%_\+.~#?&//=]*))
```
